// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx_FcdTDrlBPS3u2Kg5GbsJTMkVWkHvEU',
    appId: '1:183171561700:ios:21954b85b5aa9474d614f1',
    messagingSenderId: '183171561700',
    projectId: 'instagram-clone-e1e51',
    storageBucket: 'instagram-clone-e1e51.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx_FcdTDrlBPS3u2Kg5GbsJTMkVWkHvEU',
    appId: '1:183171561700:ios:21954b85b5aa9474d614f1',
    messagingSenderId: '183171561700',
    projectId: 'instagram-clone-e1e51',
    storageBucket: 'instagram-clone-e1e51.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuBgDxeNYhQVFazKSoOc9DkSVI31tlt1Y',
    appId: '1:183171561700:web:532719a355698d24d614f1',
    messagingSenderId: '183171561700',
    projectId: 'instagram-clone-e1e51',
    authDomain: 'instagram-clone-e1e51.firebaseapp.com',
    storageBucket: 'instagram-clone-e1e51.firebasestorage.app',
    measurementId: 'G-8WNG5MH65D',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuBgDxeNYhQVFazKSoOc9DkSVI31tlt1Y',
    appId: '1:183171561700:web:532719a355698d24d614f1',
    messagingSenderId: '183171561700',
    projectId: 'instagram-clone-e1e51',
    authDomain: 'instagram-clone-e1e51.firebaseapp.com',
    storageBucket: 'instagram-clone-e1e51.firebasestorage.app',
    measurementId: 'G-8WNG5MH65D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmzoDOS-80Gv4-2zHRC0ZsZ8mkUIRLBHs',
    appId: '1:183171561700:android:c8220f3680fb1587d614f1',
    messagingSenderId: '183171561700',
    projectId: 'instagram-clone-e1e51',
    storageBucket: 'instagram-clone-e1e51.firebasestorage.app',
  );

}